config/routes.rb
Tript::Application.routes.draw do
  get 'sessions/new'

  get 'lessons/get_content', to: 'lessons#get_content'

  get 'class/lessons', to: 'class#lessons'

  get 'subject/lessons', to: 'subject#lessons'

  get 'schools/lessons', to: 'schools#lessons'

  get 'type/lessons', to: 'type#lessons'

  resources :users, only: [:new, :create, :destroy]
  get '/users/:id' => 'users#show'
  get '/users' => 'users#index'
  post '/users/new' => 'users#create'
  get '/inbox', to: 'users#inbox', as: 'inbox'

  root             'static_pages#home'
  get 'help'    => 'static_pages#help'
  get 'about'   => 'static_pages#about'
  get 'contact' => 'static_pages#contact'
  get 'signup'  => 'users#new'
  get    'login'   => 'sessions#new'
  post   'login'   => 'sessions#create'
  delete 'logout'  => 'sessions#destroy'

  resources :lessons, only: [:new, :create, :destroy] do
    resources :comments
  end

  get '/lessons' => 'lessons#search'
  get '/lessons/:id' => 'lessons#show'
  post '/lessons/downloads/:id', to: 'lessons#download', as: :download_lesson
  get '/details/:id' => 'lessons#details'
  post '/lessons/new' => 'lessons#create'
  delete 'lessons/:id' => 'lessons#destroy'

  resources :schools

  get '/grades' => 'schools#index'

  get '/classes/:id/subjects' => 'class#subjects'

  get '/grades/name/:name' => 'schools#names'

  get '/admin/users/edit', to: 'admin#manage_user', as: 'manage_user'
  put '/admin/users', to: 'admin#update_users', as: :update_user
  get '/users/all/edit', to: 'users#edit_all', as: :edit_all
  post '/users/all/edit', to: 'users#create_by_admin'
  put '/users/all', to: 'users#update_all', as: :update_all
  get '/users/:username/downloads', to: 'users#list_of_downloads', as: :list_of_downloads
  get '/users/edit/doi-mat-khau', to: 'users#change_password', as: :change_password
  put '/users/edit', to: 'users#update_password', as: :update_password

  get '/lessons/manage/approval', to: 'lessons#approve', as: :approve
  put '/lessons/manage', to: 'lessons#update_approval', as: :update_approval
  delete '/lessons/manage/approval/:id', to: 'lessons#destroy_by_manager', as: :destroy_by_manager

  get '/tim-kiem-nang-cao', to: 'lessons#advanced_search', as: :advanced_search

  get '/:school', to: 'schools#index', as: :school_view

  namespace :api, defaults: { format: :json }, path: '/' do
    scope module: :v1 do
    end
  end

  mount Commontator::Engine => '/commontator'

  get '/schools/new', to: 'schools#new', as: :school_new
  post '/schools/new', to: 'schools#add_by_admin', as: :create_school
  put '/schools', to: 'schools#update_all', as: :update_all_school
  delete '/schools/:id', to: 'schools#destroy', as: :delete_school

  get '*unmatched_route', to: 'application#not_found'

end

app/models/lesson.rb
class Lesson < ActiveRecord::Base
  acts_as_commontable

  is_impressionable
  self.table_name = "lessons"
  mount_uploader :url, UrlUploader # Tells rails to use this uploader for this model.
  mount_uploader :represent_image, RepresentImageUploader
  belongs_to :user
  belongs_to :active_class, foreign_key: "class_id"
  accepts_nested_attributes_for :active_class
  has_many :comments, dependent: :destroy
  has_many :assignments, dependent: :destroy
  has_many :persons_in_charge, through: :assignments, source: :user, dependent: :destroy
  has_many :downloads
  has_many :download_users, through: :downloads, source: :user, dependent: :destroy
  belongs_to :approver, class_name: "User", foreign_key: "approver_id"

  validates :user_id, presence: true
  validates :url, presence: true, file_size: { less_than: 150.megabytes, message: 'File dữ liệu phải nhỏ hơn %{count}' }
  validates :represent_image, file_content_type: { allow: ['image/jpeg', 'image/png'], message: 'chỉ được sử dụng %{type}' }
  validates :name, presence: true
  validates :class_id, presence: { message: 'Lớp không được bỏ trống' }
  default_scope -> { order(created_at: :desc) }
end

app/controllers/lessons_controller.rb
require 'zip'

class LessonsController < ApplicationController
  impressionist :actions => [:show, :details]

  def index
    @lessons = Lesson.all
  end

  def new
    if logged_in?
      @lesson = Lesson.new
      @school = current_user.school
      if @school
        @classes = @school.active_classes.order(:id)
      end
      @types = Type.all
    end
  end

  def get_content
    @lessons = Lesson.all.paginate(page: params[:page], per_page: 30)
  end

  def create
    @isCreated = true;
    persons_in_charge_params = lesson_params[:persons_in_charge]
    @lesson = Lesson.new(lesson_params.except(:persons_in_charge))
    @lesson.user = current_user
    if @lesson.save
      if eval(lesson_params[:type_id]) == 1
        id = @lesson.id
        if !valid_zip?(@lesson.url.file.path)
          flash.now[:danger] = "Bài giảng không hợp lệ"
          @lesson.destroy
          path_to_lesson = @lesson.url.path
          File.delete(path_to_lesson) if File.exist?(path_to_lesson)
          @school = current_user.school
          @classes = @school.active_classes.order(:id)
          render 'new'
          return
        end
        Zip::File.open(@lesson.url.file.path) do |zipfile|
          zipfile.each do |file|
            f_path=File.join("public/uploads/#{id}/" + file.name)
            FileUtils.mkdir_p(File.dirname(f_path))
            zipfile.extract(file, f_path) unless File.exist?(f_path)
          end
        end

        if File.exists?("public/uploads/#{id}/index.html")
          File.rename("public/uploads/#{id}/index.html", "public/uploads/#{id}/index.htm")
        end
        if !File.exists?("public/uploads/#{id}/index.htm")
          flash.now[:danger] = "Bài giảng không hợp lệ"
          @lesson.destroy
          @lesson = nil
        end
      end

      if @lesson
        if @lesson.isAssignment && persons_in_charge_params.any?
          @lesson.persons_in_charge = User.where("username in (?)", persons_in_charge_params)
        end

        #redirect to lesson_path
        flash.now[:success] = "Tải lên bài giảng thành công"
      end
    end
    @school = current_user.school
    @classes = @school.active_classes.order(:id)
    render 'new'
  end

  def destroy
    @lesson = Lesson.find(params[:id])
    @lesson.destroy
    path_to_lesson = @lesson.url.path
    File.delete(path_to_lesson) if File.exist?(path_to_lesson)
    if @lesson.type_id == 1
      FileUtils.rm_rf("public/uploads/#{@lesson.id}") if File.directory?("public/uploads/#{@lesson.id}")
    end
    flash.now[:success] = "Bài giảng " + @lesson.name + " đã được xóa thành công"
    redirect_to root_path
  end

  def destroy_by_manager
    @lesson = Lesson.find(params[:id])
    @lesson.destroy
    path_to_lesson = @lesson.url.path
    File.delete(path_to_lesson) if File.exist?(path_to_lesson)
    if @lesson.type_id == 1
      FileUtils.rm_rf("public/uploads/#{@lesson.id}") if File.directory?("public/uploads/#{@lesson.id}")
    end
    flash.now[:success] = "Bài giảng " + @lesson.name + " đã được xóa thành công"
    redirect_to approve_path
  end

  def show
    @lessons = Lesson.find(params[:id])
    id = @lessons.id
    if id == 1
      redirect_to("/uploads/#{id}/index.htm")
    else
      render nothing: true
    end
  end

  def details
    @lesson = Lesson.find(params[:id])
    @school = @lesson.user.school
    @filesize = '%.2f' % (File.size(Rails.public_path.to_s + @lesson.url.url).to_f / 2**20)
    @downloads_count = Download.where(lesson_id: @lesson.id).count
    if @school.grade_id == 5
      @phongdaotao = @school
    else
      @phongdaotao = @school.phongdaotao
    end
    @comments = Comment.where(lesson_id: params[:id])
    commontator_thread_show(@lesson)

    # use for left menu
    if @school.grade_id == 5
      @phongdaotao = @school
      @classes = @school.active_classes
    else
      @phongdaotao = @school.phongdaotao
      @classes = @school.active_classes
    end
  end

  def search
    search = params[:search]
    if params[:school]
      school_id = params[:school][:id]
      type_id = params[:type][:id]
      class_id = params[:class][:id]
    end

    @lessons = Lesson.all
    if params[:school]
      if !school_id.empty?
        @lessons = Lesson.joins(:user).where(users: {school_id: params[:school][:id]})
      end
      if !class_id.empty?
        @lessons = @lessons.where(class_id: class_id)
      end
      if !type_id.empty?
        @lessons = @lessons.where(type_id: type_id)
      end
    end
    if !search.empty?
      @lessons = @lessons.where('lessons.name LIKE ?', "%#{search}%")
    end

    @lessons = @lessons.paginate(page: params[:page], per_page: 30)
    @search_content = search
  end

  def approve
    if logged_in? && is_manager?(current_user)
      @lessons = Lesson.joins(:user).where(approved: false).where(users: {school_id: current_user.school_id}).order('created_at DESC').paginate(page: params[:page], per_page: 10)
    end
  end

  def update_approval
    params['lesson'].keys.each do |id|
      @lesson = Lesson.find(id.to_i)
      @lesson.update_columns(approver_id: current_user.id)
      if !@lesson.update_columns(params['lesson'][id].permit(:approved))
        flash.now[:success] = Rails.logger.info(@lesson.errors.messages.inspect)
      end
    end
    redirect_to(approve_path)
  end

  def download
    lesson = Lesson.find(params[:id])
    download = Download.new(user_id: current_user.id, lesson_id: lesson.id)
    if download.valid?
      download.save
    end
    send_file lesson.url.path
  end

  def advanced_search

  end

  private
  def lesson_params
    params.require(:lessons).permit(:name, :url, :subject_id, :class_id, :represent_image, :type_id, :isAssignment, :persons_in_charge)
  end

  def valid_zip?(file)
    zip = Zip::File.open(file)
    true
  rescue Zip::Error
    false
  ensure
    zip.close if zip
  end

  def is_manager?(user)
    if user.nil?
      return false
    end
    if user.roles.exists?(2)
      return true
    else
      return false
    end
  end

end

app/helpers/lessons_helper.rb
module LessonsHelper
  def uploaded_lesson
    @uploaded_lesson = @lesson
  end
end

app/views/lessons/_lesson.html.erb
<div class="row lessons-row">
  <% lessons.each do |lesson| %>

      <div class="col-md-2 portfolio-item lesson-col" id="lesson-<%= lesson.id %>">
        <div class="lesson-card">
          <div class="lesson-image">
            <%= link_to image_tag(lesson.represent_image.url(:thumb)), {controller: "lessons", action: "details", id: lesson.id}, alt: lesson.name %>
          </div>
          <!--<span class="timestamp">-->
          <!--Uploaded <%= time_ago_in_words(lesson.created_at) %> ago.-->
          <!--</span>-->
          <div class="lesson-name">
            <%= link_to "#{lesson.name}", {controller: "lessons", action: "details", id: lesson.id}, alt: lesson.name %>
          </div>
        </div>
      </div>
  <% end %>
</div>
<div class="row">
  <%= js_will_paginate lessons %>
</div>

app/views/lessons/advanced_search.html.erb
<div class="row">
  <div class="col-md-6 col-md-offset-3">
    <div class="main">
      <div class="search advanced-search">
        <h1>
          <strong><font color="red">Tìm kiếm nâng cao</font> </strong>
        </h1>
        <%= form_tag lessons_path, method: 'get', class: "t1-form twitter-form", role: "search" do %>
            <label>Tên</label><%= text_field_tag :search, nil, class: "form-control", placeholder: "Tên tài liệu" %>
            <label>Trường</label> <%= collection_select :school, :id, School.all, :id, :name, {include_blank: ""}, {class: "form-control"} %>
            <label>Lớp</label> <%= collection_select :class, :id, ActiveClass.all, :id, :name, {include_blank: ""}, {class: "form-control"} %>
            <label>Loại tài
              liệu</label> <%= collection_select :type, :id, Type.all, :id, :name, {include_blank: ""}, {class: "form-control"} %>
            <%= button_tag 'Tìm kiếm <i class="glyphicon glyphicon-search"></i></button>'.html_safe, class: "btn btn-primary btn-default" %>
        <% end %>
      </div>
    </div>
  </div>
</div>

app/views/lessons/approve.html.erb
<% provide(:title, "Duyệt bài") %>
<% if logged_in? && is_manager?(current_user) %>
    <br/>
    <br/>
    <div class="row">
      <div class="table-responsive col-md-12">
        <%= form_for :lesson, :url => update_approval_path, :html => {:method => :put} do %>
            <table class="table table-hover table-striped">
              <tr>
                <th class="col-md-4">Tiêu đề</th>
                <th class="col-md-3">Người gửi</th>
                <th class="col-md-2">Ngày gửi</th>
                <th class="col-md-2">Tình trạng</th>
                <th class="col-md-1">Xóa</th>
              </tr>
              <% @lessons.each do |lesson| %>
                  <%= fields_for "lesson[]", lesson do |lesson_fields| %>
                      <tr>
                        <td><%= link_to lesson.name, {controller: "lessons", action: "details", id: lesson.id} %></td>
                        <td><%= lesson.user.name %></td>
                        <td><%= lesson.created_at.strftime("%Y-%m-%d") %></td>
                        <td><%= lesson_fields.select :approved, [["Duyệt", 1], ["Không duyệt", 0]], selected: 0 %></td>
                        <td><%= link_to "Xoá", destroy_by_manager_path(id: lesson.id), method: :delete,
                                        data: {confirm: "Bạn có chắc muốn tài liệu này không?"} %></td>
                      </tr>
                  <% end %>
              <% end %>

            </table>
            <div class="actions">
              <%= button_tag "Lưu lại", class: "btn btn-primary btn-md col-md-2 col-md-offset-5" %>
            </div>
        <% end %>
      </div>
    </div>
    <%= will_paginate @lessons %>
<% else %>
    <h3>
      Chỉ có giáo viên quản lý mới xem được trang này.</br>
    </h3>
<% end %>

app/views/lessons/details.html.erb
<div class="row">
  <div class="col-md-3">
    <h4><font color="red" style="font-weight: bolder">Thư viện Điện tử</font></h4>
    <ul class="metismenu nav nav-pills nav-stacked" id="menu">
      <% Type.all.each do |type| %>
          <li class="inactive">
            <%= link_to "#{type.name}<span class=\"glyphicon arrow\"></span>".html_safe, {controller: :type, action: 'lessons', type_id: type.id, school_id: @school.id}, remote: true %>
            <ul class="nav nav-pills nav-stacked" aria-expanded="false">
              <% @classes.each do |active_class| %>
                  <li class="inactive">
                    <% subjects = active_class.subjects %>
                    <% if subjects.any? %>
                        <%= link_to "#{active_class.name}<span class=\"glyphicon arrow\"></span>".html_safe, {controller: :class, action: 'lessons', id: active_class.id, school_id: @school.id, type_id: type.id}, remote: true %>
                        <ul class="nav nav-pills nav-stacked" aria-expanded="false">
                          <% subjects.each do |subject| %>
                              <li class="inactive">
                                <%= link_to "#{subject.subject_name}", {controller: :subject, action: 'lessons', class_id: active_class.id, subject_id: subject.id, school_id: @school.id, type_id: type.id}, remote: true %>
                              </li>
                          <% end %>
                        </ul>
                    <% else %>
                        <%= link_to "#{active_class.name}", {controller: :class, action: 'lessons', id: active_class.id, school_id: @school.id, type_id: type.id}, remote: true %>
                    <% end %>
                  </li>
              <% end %>
            </ul>
          </li>
      <% end %>
    </ul>
    <div class="divider"></div>
    <h4><font color="red" style="font-weight: bolder">Tìm kiếm</font></h4>
    <nav>
      <%= form_tag lessons_path, method: 'get', class: "nav navbar-nav navbar-left navbar-form", role: "search" do %>
          <div class="input-group">
            <%= text_field_tag :search, nil, class: "form-control", placeholder: "Tìm kiếm", value: @search_content %>
            <div class="input-group-btn">
              <div class="dropdown">
                <%= button_tag '<i class="glyphicon glyphicon-search"></i></button>'.html_safe, class: "btn btn-default" %>
                <!-- <span class="caret"></span>
                    <ul class="dropdown-menu">
                      <li><%= link_to advanced_search_path %></li>
                    </ul> -->
              </div>
            </div>
          </div>
      <% end %>
      <u><%= link_to "Tìm kiếm nâng cao", advanced_search_path %></u>
    </nav>

    <div class="divider"></div>
    <h4><font color="red" style="font-weight: bolder">Thống kê</font></h4>
    <b>
      Lượt xem: <%= Impression.count %> </br>
      Lượt xem hôm
      nay: <%= Impression.where('created_at between ? and ?', DateTime.now.beginning_of_day, DateTime.now.end_of_day).count %>
    </b>

  </div>

  <div class="col-md-9" id="content">
    <div class="row" data-no-turbolink>
      <div class="col-md-7">
        <% if @lesson.type_id == 1 %>
            <%= link_to image_tag(@lesson.represent_image.url(:thumb)), "/uploads/#{@lesson.id}/index.htm", target: "_blank" %>

            <%= link_to "Xem", "/uploads/#{@lesson.id}/index.htm", class: 'btn btn-primary', target: "_blank" %>

        <% else %>
            <% file = @lesson.url.path %>
            <% extension = File.extname(file).downcase %>
            <%= image_tag(@lesson.represent_image.url(:thumb))%>
            <% if logged_in? %>
            <div class="btn btn-primary lesson-view-popup">Xem</div>
            <% end %>
            <div id="element_to_pop_up">

              <% if extension == ".swf" %>
                  <embed width="800" height="600" src="<%= @lesson.url.url %>"
                         type="application/x-shockwave-flash"
                         allowScriptAccess="always"/>
              <% elsif extension == ".jpg" || extension == ".jpeg" || extension == ".png" || extension == ".gif" %>
                  <%= image_tag @lesson.url.url, alt: @lesson.name %>
              <% elsif extension == ".mp4" || extension == ".flv" %>
                  <video id="video-lesson" width="800" height="600" preload="auto" controls>
                    <source src="<%= @lesson.url.url %>" type="video/mp4">
                    <source src="movie.ogg" type="video/ogg">
                    Your browser does not support the video tag.
                  </video>
              <% elsif extension == ".mp3" || extension == ".wma" %>
                  <audio id="audio-lesson" style="width: 800px; height:200px" controls>
                    <source src=<%= @lesson.url.url %> type="audio/mpeg">
                    Your browser does not support the audio element.
                  </audio>
              <% elsif extension == ".doc" || extension == ".docx" || extension == ".ppt" || extension == ".pptx" || extension == ".xls" || extension == ".xlsx"%>
                  <div id="doc-container">
                    <div class="loader"></div>
                    <div id="doc-frame">
                     <!-- <iframe src="http://docs.google.com/gview?url=<%= request.base_url + @lesson.url.url %>&embedded=true" style="width:800px; height:600px;" frameborder="0"></iframe>-->
                      <iframe src="http://view.officeapps.live.com/op/view.aspx?src=<%= request.base_url + @lesson.url.url %>&embedded=true" style="width:800px; height:600px;" frameborder="0"></iframe>
                    </div>
                  </div>
              <% elsif extension == ".pdf"%>
                  <div id="doc-container">
                    <div class="loader"></div>
                    <div id="doc-frame">
                     <iframe src="http://docs.google.com/gview?url=<%= request.base_url + @lesson.url.url %>&embedded=true" style="width:800px; height:600px;" frameborder="0"></iframe>
                      <!-- <iframe id="iframe-obj" src="http://docs.google.com/gview?url=http://apelearning.vn/uploads/lesson/url/13/Tiet_29_Uoc_chung_va_boi_chung531.ppt&embedded=true" style="width:800px; height:600px;" frameborder="0"></iframe> -->
                    </div>
                  </div>
            <% end %>

            </div>
        <% end %>
        <% if logged_in? %>
            <%= link_to "Tải về", download_lesson_path(id: @lesson.id), method: :post, class: 'btn btn-primary' %>
        <% end %>
        <% if (is_manager?(current_user) && current_user.school_id == @lesson.user.school_id) %>
            <%= link_to "Xoá", @lesson, class: 'btn btn-primary', method: :delete,
                        data: {confirm: "Bạn có chắc muốn xóa tài liệu này không?"} %>
        <% end %>
      </div>
      <div class="col-md-5">
        <span><b> Tiêu đề: </b><%= @lesson.name %> </span> </br>
        <span><b> Người gửi: </b><%= @lesson.user.name %> </span> </br>
        <span><b> Ngày gửi: </b><%= @lesson.created_at.strftime("%Y-%m-%d") %> </span> </br>
        <span><b> Lượt xem: </b><%= @lesson.impressionist_count(:filter => :session_hash) %> </span> </br>
        <span><b> Lượt tải: </b><%= @downloads_count %> </span> </br>
        <span><b> Dung lượng: </b><%= @filesize %> MB </span> </br>
        <% if @lesson.approved %>
            <span><b> Tình trạng: </b>Đã duyệt </span> </br>
            <span><b> Người duyệt: </b><%= @lesson.approver.name %></span>
        <% else %>
            <span><b> Tình trạng: </b>Chưa duyệt </span> </br>
        <% end %>
      </div>
    </div>

    <div class="row">
      <div class="col-md-8">
        <%= commontator_thread(@lesson) %>
      </div>
    </div>
  </div>
</div>

app/views/lessons/get_content.js.erb
var html = "<%= j render partial: 'lessons/lesson', locals: {lessons: @lessons} %>";

$('#content').html(html);

app/views/lessons/index.html.erb
<% if is_admin?(current_user) %>
    <br/>
    <%= link_to "New Lesson", new_lesson_path, class: "btn btn-primary" %>
    <br/>
    <br/>

    <table class="table table-bordered table-striped">
      <thead>.
      <tr>
        <th>Tên</th>
        <th>Download Link</th>
        <th></th>
      </tr>
      </thead>

      <tbody>
      <% @lessons.each do |lesson| %>

          <tr>
            <td><%= lesson.name %></td>
            <td><%= link_to "Download bài giảng", lesson.url.url %></td>
            <td><%= button_to "Xóa bài giảng", lesson, method: :delete, class: "btn btn-danger", confirm: "Bạn có chắc muốn xóa \"#{lesson.name}\"?" %></td>
          </tr>

      <% end %>
      </tbody>

    </table>

<% else %>
    <div id="not-admin-div">
      <h1> Chỉ có admin mới xem được trang này </h1>
    </div>
<% end %>
<a href="#0" class="cd-top">Top</a>

app/views/lessons/new.html.erb
<% if current_user %>
	<% if @school %>
		<div id="status">
		  <% if @lesson && !@lesson.errors.empty? %>
			  <div class="alert alert-error">
				<ul>
				  <% @lesson.errors.full_messages.each do |msg| %>
					  <li><%= msg %></li>
				  <% end %>
				</ul>
			  </div>
		  <% end %>
		  <div class="row">
			<div class="col-md-6 col-md-offset-3">
			  <%= form_for :lessons, html: {multipart: true, id: "lesson_new_form"} do |f| %>
				  <%= f.label :name, "Tiêu đề" %>
				  <%= f.text_field :name, class: "form-control" %>

				  <%= f.label :class_id, "Lớp" %>
				  <% selected_class = @classes.first %>
				  <% if @isCreated %>
					  <%= f.collection_select :class_id, @classes, :id, :name, {selected: @lesson.class_id}, {class: 'upload-class form-control'} %>
				  <% else %>
					  <%= f.collection_select :class_id, @classes, :id, :name, {selected: selected_class.id}, {class: 'upload-class form-control'} %>
				  <% end %>

				  <%= f.label :subject_id, "Môn học" %>
				  <% if @isCreated %>
					  <% if @lesson.subject_id %>
						  <%= f.collection_select :subject_id, @lesson.active_class.subjects, :id, :subject_name, {selected: @lesson.subject_id}, {:class => 'upload-subject form-control'} %>
					  <% else %>
						  <%= f.collection_select :subject_id, @lesson.active_class.subjects, :id, :subject_name, {}, {:class => 'upload-subject form-control'} %>
					  <% end %>
				  <% else %>
					  <%= f.collection_select :subject_id, selected_class.subjects, :id, :subject_name, {}, {:class => 'upload-subject form-control'} %>
				  <% end %>

				  <%= f.label :type_id, "Loại tài liệu" %>
				  <% if @isCreated %>
					  <%= f.collection_select :type_id, Type.all, :id, :name, {selected: @lesson.type_id}, class: "form-control" %>
				  <% else %>
					  <%= f.collection_select :type_id, Type.all, :id, :name, {}, class: "form-control" %>
				  <% end %>

				  <%= f.label :attachment, "File dữ liệu" %>
				  <%= f.file_field :url %>
				  <div class="progress">
					<div class="bar"></div>
					<div class="percent">0%</div>
				  </div>

				  <%= f.label :represent_image, "Ảnh đại diện" %>
				  <%= f.file_field :represent_image, accept: 'image/png,image/jpeg' %>

				  <%= f.check_box :isAssignment, id: "assignment-checkbox" %> <label> Gửi tới </label>

				  <div id="persons-in-charge-div">
					<%= f.label :school, "Chọn trường" %>
					<% selected_school = School.first %>
					<%= f.collection_select :school, School.all, :id, :name, {selected: selected_school.id}, {id: "person_in_charge_school", class: "form-control"} %>

					<%= f.label :persons_in_charge, "Chọn người nhận" %>
					<%= f.collection_select :persons_in_charge, selected_school.users, :username, :name, {}, {id: "persons-in-charge-name", class: "textarea form-control"} %>
				  </div>

				  </br>
				  <%= f.submit "Tải lên", class: "btn btn-primary", id: "lesson_upload", data: {disable_with: "Đang tải lên..."} %>
			  <% end %>
			</div>
		  </div>
		</div>
	<% else %>
		<h1> Bạn không có quyền đăng tải tài liệu</h1>
	<% end %>
<% else %>
    <h1> Bạn phải đăng nhập để đăng tải tài liệu</h1>
<% end %>

app/views/lessons/search.html.erb
<div class="row">
  <aside class="col-md-3">
    <section class="user_info">
      <h3><strong>
        Kết quả tìm kiếm
      </strong>
      </h3>
    </section>
  </aside>
  <div class="col-md-9">
    <% if @lessons.any? %>
        <h3>Bài giảng (<%= @lessons.count %>)</h3>

        <div class="row" id="lessons-content">
          <%= render partial: 'lessons/lesson', locals: {lessons: @lessons} %>
        </div>
    <% end %>
  </div>
</div>

app/views/lessons/search.js.erb
var html = "<%= j render partial: 'lessons/lesson', locals: {lessons: @lessons}  %>";

$('#lessons-content').html(html);