config/routes.rb
Tript::Application.routes.draw do
  get 'sessions/new'

  get 'lessons/get_content', to: 'lessons#get_content'

  get 'class/lessons', to: 'class#lessons'

  get 'subject/lessons', to: 'subject#lessons'

  get 'schools/lessons', to: 'schools#lessons'

  get 'type/lessons', to: 'type#lessons'

  resources :users, only: [:new, :create, :destroy]
  get '/users/:id' => 'users#show'
  get '/users' => 'users#index'
  post '/users/new' => 'users#create'
  get '/inbox', to: 'users#inbox', as: 'inbox'

  root             'static_pages#home'
  get 'help'    => 'static_pages#help'
  get 'about'   => 'static_pages#about'
  get 'contact' => 'static_pages#contact'
  get 'signup'  => 'users#new'
  get    'login'   => 'sessions#new'
  post   'login'   => 'sessions#create'
  delete 'logout'  => 'sessions#destroy'

  resources :lessons, only: [:new, :create, :destroy] do
    resources :comments
  end

  get '/lessons' => 'lessons#search'
  get '/lessons/:id' => 'lessons#show'
  post '/lessons/downloads/:id', to: 'lessons#download', as: :download_lesson
  get '/details/:id' => 'lessons#details'
  post '/lessons/new' => 'lessons#create'
  delete 'lessons/:id' => 'lessons#destroy'

  resources :schools

  get '/grades' => 'schools#index'

  get '/classes/:id/subjects' => 'class#subjects'

  get '/grades/name/:name' => 'schools#names'

  get '/admin/users/edit', to: 'admin#manage_user', as: 'manage_user'
  put '/admin/users', to: 'admin#update_users', as: :update_user
  get '/users/all/edit', to: 'users#edit_all', as: :edit_all
  post '/users/all/edit', to: 'users#create_by_admin'
  put '/users/all', to: 'users#update_all', as: :update_all
  get '/users/:username/downloads', to: 'users#list_of_downloads', as: :list_of_downloads
  get '/users/edit/doi-mat-khau', to: 'users#change_password', as: :change_password
  put '/users/edit', to: 'users#update_password', as: :update_password

  get '/lessons/manage/approval', to: 'lessons#approve', as: :approve
  put '/lessons/manage', to: 'lessons#update_approval', as: :update_approval
  delete '/lessons/manage/approval/:id', to: 'lessons#destroy_by_manager', as: :destroy_by_manager

  get '/tim-kiem-nang-cao', to: 'lessons#advanced_search', as: :advanced_search

  get '/:school', to: 'schools#index', as: :school_view

  namespace :api, defaults: { format: :json }, path: '/' do
    scope module: :v1 do
    end
  end

  mount Commontator::Engine => '/commontator'

  get '/schools/new', to: 'schools#new', as: :school_new
  post '/schools/new', to: 'schools#add_by_admin', as: :create_school
  put '/schools', to: 'schools#update_all', as: :update_all_school
  delete '/schools/:id', to: 'schools#destroy', as: :delete_school

  get '*unmatched_route', to: 'application#not_found'

end

app/models/school.rb
class School < ActiveRecord::Base
  validates :name, presence: true, uniqueness: true
  validates :grade_id, presence: true

  extend FriendlyId
  friendly_id :name, use: :slugged
  belongs_to :grade
  belongs_to :phongdaotao, class_name: "School", foreign_key: "pdt_id"
  has_many :belonged_school, class_name: "School", foreign_key: "pdt_id", dependent: :nullify
  has_many :users, foreign_key: "school_id", dependent: :nullify
  def active_classes
    return grade.active_classes
  end
end

app/controllers/schools_controller.rb
class SchoolsController < ApplicationController
  def index
    #grade = School.all
    #render json: grade
    begin
      @school = School.friendly.find(params[:school])
    rescue ActiveRecord::RecordNotFound => e
      render file: 'public/404.html'
    else
      if @school.grade_id == 5
        @phongdaotao = @school
        @classes = @school.active_classes
        @type_lessons = Array.new
        @type = Type.all
        @type.each do |type|
          type_lesson = TypeLesson.new
          type_lesson.type = type
          quantity = Lesson.joins(user: :school).where("schools.pdt_id = ? OR schools.id = ?", @school.id, @school.id).where(type_id: type.id).size
          lessons = Lesson.joins(user: :school).where("schools.pdt_id = ? OR schools.id = ?", @school.id, @school.id).where(type_id: type.id).limit(10)
          type_lesson.quantity = quantity
          type_lesson.lessons = lessons
          @type_lessons.push(type_lesson)
        end
      elsif @school.grade_id == 7
        @classes = ActiveClass.all.order('id ASC')
        @type_lessons = Array.new
        @type = Type.all
        @type.each do |type|
          type_lesson = TypeLesson.new
          type_lesson.type = type
          quantity = Lesson.joins(:user).where(type_id: type.id).size
          lessons = Lesson.joins(:user).where(type_id: type.id).limit(10)
          type_lesson.quantity = quantity
          type_lesson.lessons = lessons
          @type_lessons.push(type_lesson)
        end
      else
        @phongdaotao = @school.phongdaotao
        @classes = @school.active_classes
        @type_lessons = Array.new
        @type = Type.all
        @type.each do |type|
          type_lesson = TypeLesson.new
          type_lesson.type = type
          quantity = Lesson.joins(:user).where(users: {school_id: @school.id}, type_id: type.id).size
          lessons = Lesson.joins(:user).where(users: {school_id: @school.id}, type_id: type.id).limit(10)
          type_lesson.quantity = quantity
          type_lesson.lessons = lessons
          @type_lessons.push(type_lesson)
        end
      end
    end
  end

  def classes
    grade = School.find(params[:id])
    render json: grade.active_classes
  end

  def subjects
    grade = School.find(params[:id])
    render json: grade.subjects
  end

  def names
    render json: School.where(name: params[:name]).take
  end

  def lessons1
    grade = School.where(name: params[:name]).take
    classes = grade.active_classes
    lessons = Array.new

    classes.each do |cl|
      class_lesson = ClassLesson.new
      class_lesson.class = cl.name
      class_lesson.lessons = cl.lessons.limit(3)
      class_lesson.quantity = cl.lessons.count
      lessons.push(class_lesson)
    end

    render json: lessons
  end

  def lessons
    school = School.find(params[:id])
    @classes = school.active_classes
    @lessons = Array.new

    @classes.each do |cl|
      class_lesson = ClassLesson.new
      class_lesson.class = cl.name
      class_lesson.lessons = Lesson.joins(:user).where(users: {school_id: school.id}, class_id: cl.id).limit(10)
      class_lesson.quantity = Lesson.joins(:user).where(users: {school_id: school.id}, class_id: cl.id).size
      @lessons.push(class_lesson)
    end
  end

  def new
    @schools = School.all
  end

  def update_all
    params['school'].keys.each do |slug|
      @school = School.friendly.find(slug.to_s)
      if !@school.update_columns(params['school'][slug].permit(:name, :grade_id, :pdt_id))
        flash[:success] = Rails.logger.info(@school.errors.messages.inspect)
      end
    end
    redirect_to school_new_path
  end

  def destroy
    School.find(params[:id]).destroy
    flash[:success] = "Xóa thành công"
    redirect_to school_new_path
  end

  def add_by_admin
    @school = School.new(school_params)
    if @school.save
      flash[:success] = "Đã thêm trường thành công!"
    end

    redirect_to school_new_path
  end

  private
  def school_params
    params.require(:school_new).permit(:name, :grade_id, :pdt_id)
  end

end

app/helpers/schools_helper.rb
module SchoolsHelper
end

app/views/schools/_lessons.html.erb
<% @lessons.each do |class_lesson| %>
    <div class="row">
      <h3> <%= link_to "#{class_lesson.class}<span class=\"glyphicon arrow\"></span>".html_safe, {controller: :class, action: 'lessons', name: class_lesson.class}, remote: true %>
        ( <%= class_lesson.quantity %> ) </h3>
      <% if class_lesson.lessons.any? %>
          <div class="row lessons-row">
            <% class_lesson.lessons.each do |lesson| %>

                <div class="col-md-2 portfolio-item lesson-col" id="lesson-<%= lesson.id %>">
                  <div class="lesson-card">
                    <div class="lesson-image">
                      <%= link_to image_tag(lesson.represent_image.url(:thumb)), {controller: :lessons, action: 'details', id: lesson.id}, alt: lesson.name %>
                    </div>
                    <!--<span class="timestamp">-->
                    <!--Uploaded <%= time_ago_in_words(lesson.created_at) %> ago.-->
                    <!--</span>-->
                    <div class="lesson-name">
                      <%= lesson.name %>
                    </div>
                  </div>
                </div>
            <% end %>
          </div>
      <% else %>
          <h3 class="no-lesson-info"> Dữ liệu đang cập nhật</h3>
      <% end %>
    </div>
<% end %>

app/views/schools/index.html.erb
<% provide(:title, "#{@school.name}") %>
<div class="row">
  <div class="col-md-3">
    <h4><font color="red" style="font-weight: bolder">Thư viện Điện tử</font></h4>
    <ul class="metismenu nav nav-pills nav-stacked" id="menu">
      <% Type.all.each do |type| %>
          <li class="inactive">
            <%= link_to "#{type.name}<span class=\"glyphicon arrow\"></span>".html_safe, {controller: :type, action: 'lessons', type_id: type.id, school_id: @school.id}, remote: true %>
            <ul class="nav nav-pills nav-stacked" aria-expanded="false">
              <% @classes.each do |active_class| %>
                  <li class="inactive">
                    <% subjects = active_class.subjects %>
                    <% if subjects.any? %>
                        <%= link_to "#{active_class.name}<span class=\"glyphicon arrow\"></span>".html_safe, {controller: :class, action: 'lessons', id: active_class.id, school_id: @school.id, type_id: type.id}, remote: true %>
                        <ul class="nav nav-pills nav-stacked" aria-expanded="false">
                          <% subjects.each do |subject| %>
                              <li class="inactive">
                                <%= link_to "#{subject.subject_name}", {controller: :subject, action: 'lessons', class_id: active_class.id, subject_id: subject.id, school_id: @school.id, type_id: type.id}, remote: true %>
                              </li>
                          <% end %>
                        </ul>
                    <% else %>
                        <%= link_to "#{active_class.name}", {controller: :class, action: 'lessons', id: active_class.id, school_id: @school.id, type_id: type.id}, remote: true %>
                    <% end %>
                  </li>
              <% end %>
            </ul>
          </li>
      <% end %>
    </ul>
    <div class="divider"></div>
    <h4><font color="red" style="font-weight: bolder">Tìm kiếm</font></h4>
    <nav>
      <%= form_tag lessons_path, method: 'get', class: "nav navbar-nav navbar-left navbar-form", role: "search" do %>
          <div class="input-group">
            <%= text_field_tag :search, nil, class: "form-control", placeholder: "Tìm kiếm", value: @search_content %>
            <div class="input-group-btn">
              <div class="dropdown">
                <%= button_tag '<i class="glyphicon glyphicon-search"></i></button>'.html_safe, class: "btn btn-default" %>
                <!-- <span class="caret"></span>
                    <ul class="dropdown-menu">
                      <li><%= link_to advanced_search_path %></li>
                    </ul> -->
              </div>
            </div>
          </div>
      <% end %>
      <u><%= link_to "Tìm kiếm nâng cao", advanced_search_path %></u>
    </nav>

    <div class="divider"></div>
    <h4><font color="red" style="font-weight: bolder">Thống kê</font></h4>
    <b>
      Lượt xem: <%= Impression.count %> </br>
      Lượt xem hôm nay: <%= Impression.where('created_at between ? and ?', DateTime.now.beginning_of_day, DateTime.now.end_of_day).count %>
    </b>

  </div>
  <div class="col-md-9" id="content">
    <% @type_lessons.each do |type_lesson| %>
        <div class="row">
          <h3> <%= link_to "#{type_lesson.type.name}<span class=\"glyphicon arrow\"></span>".html_safe, {controller: :type, action: 'lessons', type_id: type_lesson.type.id, school_id: @school.id}, remote: true %>
            ( <%= type_lesson.quantity %> ) </h3>
          <% if type_lesson.lessons.any? %>
              <div class="row lessons-row">
                <% type_lesson.lessons.each do |lesson| %>
                    <div class="col-md-2 portfolio-item lesson-col" id="lesson-<%= lesson.id %>">
                      <div class="lesson-card">
                        <div class="lesson-image">
                          <%= link_to image_tag(lesson.represent_image.url(:thumb)), {controller: :lessons, action: 'details', id: lesson.id}, alt: lesson.name %>
                        </div>
                        <div class="lesson-name">
                          <%= link_to "#{lesson.name}", {controller: :lessons, action: 'details', id: lesson.id}, alt: lesson.name %>
                        </div>
                      </div>
                    </div>
                <% end %>
              </div>
          <% else %>
              <h3 class="no-lesson-info"> Dữ liệu đang cập nhật</h3>
          <% end %>
        </div>
    <% end %>
  </div>
</div>
<a href="#0" class="cd-top">Top</a>

app/views/schools/lessons.js.erb
var html = "<%= j render partial: 'lessons', locals: {lessons: @lessons} %>";

$('#content').html(html);

app/views/schools/new.html.erb
<% if logged_in? && is_admin?(current_user) %>
    <br/>
    <br/>
    <div class="row">
      <div class="table-responsive col-md-10">
        <%= form_for :school, :url => update_all_school_path, :html => {:method => :put} do %>
            <table class="table table-hover table-striped">
              <tr>
                <th class="col-md-2">Tên đơn vị</th>
                <th class="col-md-3">Khối</th>
                <th class="col-md-3">Đơn vị quản lý</th>
                <th class="col-md-2">Xóa</th>
              </tr>
              <% @schools.each do |school| %>
                  <%= fields_for "school[]", school do |school_fields| %>
                      <tr>
                        <td><%= school_fields.text_field :name %></td>
                        <td><%= school_fields.collection_select :grade_id, Grade.all, :id, :name %></td>
                        <td><%= school_fields.collection_select :pdt_id, School.where("grade_id = '5' or grade_id = '7'"), :id, :name %></td>
                        <td><%= link_to "Xoá", delete_school_path(id: school.id), method: :delete,
                                        data: { confirm: "Bạn có chắc không?" } %>
                        </td>
                      </tr>
                  <% end %>
              <% end %>
            </table>
            <div class="actions">
              <%= button_tag "Lưu lại", class: "btn btn-primary btn-md col-md-2 col-md-offset-5" %>
            </div>
        <% end %>
      </div>
    </div>
    <div class="divider"></div>
    <div class="row">
      <div class=col-sm-8>
        <% if @school && !@school.errors.empty? %>
            <div class="alert alert-error">
              <ul>
                <% @school.errors.full_messages.each do |msg| %>
                    <li><%= msg %></li>
                <% end %>
              </ul>

            </div>
        <% end %>
        <div class="divider"></div>
        <%= form_for(:school_new) do |f| %>
            <%= render 'shared/error_messages' %>
            <%= f.label :name, "Tên đơn vị" %>
            <%= f.text_field :name, class: 'form-control' %>

            <%= f.label :grade, "Khối" %>
            <%= f.collection_select :grade_id, Grade.all, :id, :name, {}, {class: 'form-control'} %>

            <%= f.label :pdt, "Đơn vị quản lý" %>
            <%= f.collection_select :pdt_id, School.where("grade_id = '5' or grade_id = '7'"), :id, :name, {include_blank: true}, {class: 'form-control'} %>

            <%= button_tag "Thêm", class: "btn btn-primary" %>
        <% end %>
      </div>
    </div>
<% else %>
    <h3>Chỉ có admin mới xem được trang này</h3>
<% end %>